# Site settings
title: "Yan M. Nunes"
description: "The résumé of an awesome developer"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Yan M. Nunes"
resume_title:                   "Fullstack Developer"
resume_contact_email:           "me@yannunes.com"
resume_contact_telephone:       "+55 (71) 99642-7865"
#resume_contact_address:         ""
resume_header_contact_info: "+55 (71) 99642-7865 | me@yannunes.com"
resume_header_intro: "<p>I'm a Full Stack Developer with an unending hunger for knowledge and unrivaled love for JavaScript. I have experience building high quality web-applications and website, as well as building cross-platform Mobile Apps. I like to work in a team that is very passionate about their work and cares about how the user will interact with the final product. Responsive designs with a mobile-first mindset are my main focus when creating an UI.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/midyan/resume"
  # resume_twitter_url:           ""
  # resume_dribbble_url:          ""
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/yannunes/?locale=en_US"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://yannunes.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
