# Site settings
title: 'Yan M. Nunes'
description: 'The résumé of an awesome developer'

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    style: compressed

# Resume settings
resume_avatar: 'true'
resume_name: 'Yan M. Nunes'
resume_title: 'Software Engineer and Technology Enthusiast'
resume_contact_email: 'yannunes@gmail.com'
resume_contact_telephone: '+49 172 295 16 46'
#resume_contact_address:         ""
resume_header_contact_info: '+49 172 295 16 46 | yannunes@gmail.com'
# resume_header_intro: "<p align='center'><h3>Test Oriented Development | Targeting Mobile/Web Applications</h3></p><p align='justify'></p>"
resume_header_intro: "<p align='center'><h3>Test Oriented Development | Focus on improving team perfomance and leading by example</h3></p><div>Eager to learn, innovative professional with a can-do attitude and proven experience in leading a development squad under a SCRUM environment. Puts great value in having the entire codebase tested and enjoys automating whatever is possible from the development workflow, making everyone's life easier. Believes that knowing how to deploy your application to the world is just as important as the development itself.</div>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work: 'yes'

# Decide which sections to use
# comment out to hide
resume_section_experience: true
resume_section_education: true
resume_section_projects: true
resume_section_skills: true
resume_section_recognition: false
resume_section_links: false
resume_section_associations: false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
    resume_github_url: 'https://github.com/midyan'
    # resume_twitter_url:           ""
    # resume_dribbble_url:          ""
    # resume_facebook_url:          "insert Facebook URL here"
    resume_linkedin_url: 'https://www.linkedin.com/in/yannunes/?locale=en_US'
    # resume_instagram_url:         "insert your Instagram URL here"
    # resume_website_url:           "http://yannunes.com"
resume_print_social_links: true

# Design settings
resume_theme: default
# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
